/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 目前登入者（前端 role-gating 用）。
         */
        get: operations["me_api_v2_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rule-sets/{code}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rule Set Options
         * @description 下拉用：含 label（中/英）的選項清單，從 DB 載（FE-1 正式版，與 calculate 同源）。
         */
        get: operations["rule_set_options_api_v2_rule_sets__code__options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minimost/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate */
        post: operations["calculate_api_v2_minimost_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/level/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Level */
        post: operations["validate_level_api_v2_level_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/level/build-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Level Output */
        post: operations["build_level_output_api_v2_level_build_output_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Worksheet */
        get: operations["read_worksheet_api_v2_worksheets__worksheet_id__get"];
        /** Save Worksheet */
        put: operations["save_worksheet_api_v2_worksheets__worksheet_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Worksheet Versions */
        get: operations["worksheet_versions_api_v2_worksheets__worksheet_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Worksheet */
        post: operations["publish_worksheet_api_v2_worksheets__worksheet_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Worksheet */
        post: operations["clone_worksheet_api_v2_worksheets__worksheet_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vocab */
        get: operations["list_vocab_api_v2_vocab_get"];
        put?: never;
        /** Create Vocab */
        post: operations["create_vocab_api_v2_vocab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/vocab/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft Delete Vocab */
        delete: operations["soft_delete_vocab_api_v2_vocab__item_id__delete"];
        options?: never;
        head?: never;
        /** Patch Vocab */
        patch: operations["patch_vocab_api_v2_vocab__item_id__patch"];
        trace?: never;
    };
    "/api/v2/motion-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description 標準範本（所有人）＋ 自己的草稿（僅擁有者）。
         */
        get: operations["list_templates_api_v2_motion_templates_get"];
        put?: never;
        /**
         * Create Template
         * @description 一律建為個人草稿（owner=建立者）；要成標準走 /promote。
         */
        post: operations["create_template_api_v2_motion_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/motion-templates/{template_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote Template
         * @description 草稿 → 廠標準（manager+）。
         */
        post: operations["promote_template_api_v2_motion_templates__template_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/motion-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_v2_motion_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Patch Template */
        patch: operations["patch_template_api_v2_motion_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v2/motion-templates/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match Templates */
        post: operations["match_templates_api_v2_motion_templates_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/export/wi-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wi Preview */
        get: operations["wi_preview_api_v2_worksheets__worksheet_id__export_wi_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Excel */
        get: operations["export_excel_api_v2_worksheets__worksheet_id__export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/export/lb-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Lb Csv */
        get: operations["export_lb_csv_api_v2_worksheets__worksheet_id__export_lb_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/worksheets/{worksheet_id}/export/lb-api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Lb Api */
        post: operations["export_lb_api_api_v2_worksheets__worksheet_id__export_lb_api_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v2_imports_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/{import_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Map Columns */
        post: operations["map_columns_api_v2_imports__import_id__map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_api_v2_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/profiles/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_v2_imports_profiles_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_api_v2_imports_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/imports/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Profile */
        delete: operations["delete_profile_api_v2_imports_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rule-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rule Sets */
        get: operations["list_rule_sets_api_v2_rule_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rule-sets/{code}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Full */
        get: operations["get_full_api_v2_rule_sets__code__full_get"];
        /** Put Full */
        put: operations["put_full_api_v2_rule_sets__code__full_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rule-sets/{code}/clone-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Draft */
        post: operations["clone_draft_api_v2_rule_sets__code__clone_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rule-sets/{code}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v2_rule_sets__code__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v2_admin_users_get"];
        put?: never;
        /** Upsert User */
        post: operations["upsert_user_api_v2_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/admin/users/{employee_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_api_v2_admin_users__employee_no__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ASlot */
        ASlot: {
            /**
             * Reach Cm
             * @default 0
             */
            reach_cm: number;
            /**
             * Twist Deg
             * @default 0
             */
            twist_deg: number;
            /**
             * Foot Cm
             * @default 0
             */
            foot_cm: number;
        };
        /** AppUserOut */
        AppUserOut: {
            /** Employee No */
            employee_no: string;
            /** External User Id */
            external_user_id: string | null;
            /** Display Name */
            display_name: string | null;
            /** Roles */
            roles: string[];
            /** Site Ids */
            site_ids: string[];
            /** Is Active */
            is_active: boolean;
        };
        /** AppUserPatchIn */
        AppUserPatchIn: {
            /** Roles */
            roles?: string[] | null;
            /** Site Ids */
            site_ids?: string[] | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Display Name */
            display_name?: string | null;
        };
        /** AppUserUpsertIn */
        AppUserUpsertIn: {
            /** Employee No */
            employee_no: string;
            /** Display Name */
            display_name?: string | null;
            /** Roles */
            roles?: string[];
            /** Site Ids */
            site_ids?: string[];
        };
        /** BSlot */
        BSlot: {
            /** B Code */
            b_code?: string | null;
        };
        /** Body_upload_api_v2_imports_upload_post */
        Body_upload_api_v2_imports_upload_post: {
            /** File */
            file: string;
        };
        /** CalculateResponse */
        CalculateResponse: {
            /** Seq */
            seq: string;
            /** Rule Set Code */
            rule_set_code: string;
            /** Total Tmu */
            total_tmu: number;
            /** Total Seconds */
            total_seconds: number;
            /** Tech Line */
            tech_line: string;
            /** Breakdown */
            breakdown: components["schemas"]["SlotBreakdown"][];
        };
        /** CloneDraftIn */
        CloneDraftIn: {
            /** New Code */
            new_code: string;
            /** Name Zh */
            name_zh?: string | null;
        };
        /**
         * CycleIn
         * @description 一條 GM/CM cycle。GM 用 a3/b4/p5；CM 用 m3/x4/i5（依 seq 取用）。
         */
        CycleIn: {
            /**
             * Seq
             * @enum {string}
             */
            seq: "GM" | "CM";
            /**
             * Rule Set Code
             * @default MINIMOST_FACTORY_V1
             */
            rule_set_code: string;
            a0?: components["schemas"]["ASlot"];
            b1?: components["schemas"]["BSlot"];
            g2?: components["schemas"]["GSlot"];
            a3?: components["schemas"]["ASlot"] | null;
            m3?: components["schemas"]["MSlot"] | null;
            b4?: components["schemas"]["BSlot"] | null;
            x4?: components["schemas"]["XSlot"] | null;
            p5?: components["schemas"]["PSlot"] | null;
            i5?: components["schemas"]["ISlot"] | null;
            a6?: components["schemas"]["ASlot"];
            /**
             * Frequency
             * @default 1
             */
            frequency: number;
            /** Simo Group Id */
            simo_group_id?: string | null;
        };
        /** GSlot */
        GSlot: {
            /** G Code */
            g_code?: string | null;
            /** Modifiers */
            modifiers?: {
                [key: string]: boolean;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ISlot */
        ISlot: {
            /** I Code */
            i_code?: string | null;
        };
        /** LevelFieldsIn */
        LevelFieldsIn: {
            /**
             * Coefficient
             * @default 1
             */
            coefficient: number;
            /** Ascription */
            ascription?: string | null;
            /** Level */
            level?: string | null;
            /** Countersignature */
            countersignature?: string | null;
            /** Parent Countersignature */
            parent_countersignature?: string | null;
            /** Order */
            order?: number | null;
            /** Number */
            number?: string | null;
            /** Number Count */
            number_count?: number | null;
            /**
             * Machine Count
             * @default 1
             */
            machine_count: number;
            /**
             * Manpower
             * @default 1
             */
            manpower: number;
        };
        /** LevelIssueOut */
        LevelIssueOut: {
            /** Code */
            code: string;
            /** Row Index */
            row_index: number;
            /** Message */
            message: string;
        };
        /** LevelOutputResponse */
        LevelOutputResponse: {
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            }[];
            /** Precedence Edges */
            precedence_edges: {
                [key: string]: string;
            }[];
            /** Groups */
            groups: {
                [key: string]: unknown;
            }[];
            /** Cub Groups */
            cub_groups: {
                [key: string]: string[];
            };
            /** Sub Groups */
            sub_groups: {
                [key: string]: string[];
            };
            /** Group Parents */
            group_parents: {
                [key: string]: string;
            };
            /** Number Constraints */
            number_constraints: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** LevelRowIn */
        LevelRowIn: {
            /** Content */
            content: string;
            /**
             * Raw Seconds
             * @default 1
             */
            raw_seconds: number;
            /**
             * Coefficient
             * @default 1
             */
            coefficient: number;
            /** Number */
            number?: string | null;
            /** Number Count */
            number_count?: number | null;
            /** Ascription */
            ascription?: string | null;
            /** Level */
            level?: string | null;
            /** Countersignature */
            countersignature?: string | null;
            /** Parent Countersignature */
            parent_countersignature?: string | null;
            /** Order */
            order?: number | null;
        };
        /** LevelValidateResponse */
        LevelValidateResponse: {
            /** Valid */
            valid: boolean;
            /** Issues */
            issues: components["schemas"]["LevelIssueOut"][];
        };
        /** MComponent */
        MComponent: {
            /** Verb Code */
            verb_code?: string | null;
            /**
             * Distance Cm
             * @default 0
             */
            distance_cm: number;
            /**
             * Angle Deg
             * @default 0
             */
            angle_deg: number;
            /**
             * Revolutions
             * @default 1
             */
            revolutions: number;
            /**
             * Diameter Cm
             * @default 0
             */
            diameter_cm: number;
        };
        /** MSlot */
        MSlot: {
            /** M Components */
            m_components?: components["schemas"]["MComponent"][];
        };
        /** MapIn */
        MapIn: {
            /** Sheet */
            sheet: string;
            /** Header Row */
            header_row: number;
            /** Column Map */
            column_map: {
                [key: string]: number;
            };
            /**
             * Time Unit
             * @default sec
             */
            time_unit: string;
        };
        /** MatchHit */
        MatchHit: {
            template: components["schemas"]["MotionTemplateOut"];
            /** Score */
            score: number;
            /** Matched Keywords */
            matched_keywords: string[];
        };
        /**
         * MatchIn
         * @description 匯入用：以描述比對範本（P2）。
         */
        MatchIn: {
            /** Description */
            description: string;
            /**
             * Limit
             * @default 3
             */
            limit: number;
        };
        /** MotionTemplateIn */
        MotionTemplateIn: {
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en?: string | null;
            /** Category */
            category?: string | null;
            /** Keywords */
            keywords?: string[];
            /** Seq Kind */
            seq_kind: string;
            cycle_template: components["schemas"]["CycleIn"];
        };
        /** MotionTemplateOut */
        MotionTemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string | null;
            /** Category */
            category: string | null;
            /** Keywords */
            keywords: string[];
            /** Seq Kind */
            seq_kind: string;
            /** Cycle Template */
            cycle_template: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Owner */
            owner: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** MotionTemplatePatchIn */
        MotionTemplatePatchIn: {
            /** Name Zh */
            name_zh?: string | null;
            /** Name En */
            name_en?: string | null;
            /** Category */
            category?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Seq Kind */
            seq_kind?: string | null;
            cycle_template?: components["schemas"]["CycleIn"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PSlot */
        PSlot: {
            /** P Base Code */
            p_base_code?: string | null;
            /** P Addon Codes */
            p_addon_codes?: string[];
            /**
             * Precision
             * @default false
             */
            precision: boolean;
        };
        /** PreviewOut */
        PreviewOut: {
            /**
             * Import Id
             * Format: uuid
             */
            import_id: string;
            /** Fields */
            fields: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** N */
            n: number;
            /** Warnings */
            warnings: string[];
        };
        /** ProfileIn */
        ProfileIn: {
            /** Name */
            name: string;
            /** Sheet Hint */
            sheet_hint?: string | null;
            /** Header Row */
            header_row?: number | null;
            /** Column Map */
            column_map: {
                [key: string]: number;
            };
            /**
             * Time Unit
             * @default sec
             */
            time_unit: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Sheet Hint */
            sheet_hint: string | null;
            /** Header Row */
            header_row: number | null;
            /** Column Map */
            column_map: {
                [key: string]: number;
            };
            /** Time Unit */
            time_unit: string | null;
            /** Owner */
            owner: string | null;
        };
        /** SheetPreview */
        SheetPreview: {
            /** Name */
            name: string;
            /** Grid */
            grid: unknown[][];
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
        };
        /** SlotBreakdown */
        SlotBreakdown: {
            /** Letter */
            letter: string;
            /** Tmu */
            tmu: number;
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Import Id
             * Format: uuid
             */
            import_id: string;
            /** Source Name */
            source_name: string | null;
            /** Target Fields */
            target_fields?: string[];
            /** Required Fields */
            required_fields?: string[];
            /** Sheets */
            sheets: components["schemas"]["SheetPreview"][];
            /** Suggested Sheet */
            suggested_sheet: string | null;
            /** Suggested Header Row */
            suggested_header_row: number | null;
            /** Profiles */
            profiles?: components["schemas"]["ProfileOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabItemIn */
        VocabItemIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "object" | "component" | "tool" | "from" | "to" | "hand";
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en?: string | null;
            /** External Code */
            external_code?: string | null;
            /**
             * Source System
             * @default local
             */
            source_system: string;
            /** Site Id */
            site_id?: string | null;
        };
        /** VocabItemOut */
        VocabItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Name Zh */
            name_zh: string;
            /** Name En */
            name_en: string | null;
            /** External Code */
            external_code: string | null;
            /** Source System */
            source_system: string;
            /** Is Active */
            is_active: boolean;
        };
        /** VocabPatchIn */
        VocabPatchIn: {
            /** Name Zh */
            name_zh?: string | null;
            /** Name En */
            name_en?: string | null;
            /** External Code */
            external_code?: string | null;
        };
        /** WiRowSaveIn */
        WiRowSaveIn: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seq No */
            seq_no: number;
            /** Sub Activity */
            sub_activity?: string | null;
            /** Key Parts */
            key_parts?: string | null;
            /** Hand */
            hand?: string | null;
            /**
             * Object Vocab Id
             * Format: uuid
             */
            object_vocab_id: string;
            /** From Vocab Id */
            from_vocab_id?: string | null;
            /** To Vocab Id */
            to_vocab_id?: string | null;
            /** Tool Vocab Id */
            tool_vocab_id?: string | null;
            /**
             * Frequency
             * @default 1
             */
            frequency: number;
            /** Simo Group Id */
            simo_group_id?: string | null;
            /** Narrative */
            narrative?: string | null;
            cycle: components["schemas"]["CycleIn"];
            level?: components["schemas"]["LevelFieldsIn"];
        };
        /** WorksheetReadOut */
        WorksheetReadOut: {
            /**
             * Worksheet Id
             * Format: uuid
             */
            worksheet_id: string;
            /** Status */
            status: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Total Tmu */
            total_tmu: number;
        };
        /** WorksheetSaveIn */
        WorksheetSaveIn: {
            /** Rows */
            rows?: components["schemas"]["WiRowSaveIn"][];
        };
        /** XSlot */
        XSlot: {
            /** X Code */
            x_code?: string | null;
            /**
             * X Seconds
             * @default 0
             */
            x_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v2_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    rule_set_options_api_v2_rule_sets__code__options_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_api_v2_minimost_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CycleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_level_api_v2_level_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelRowIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_level_output_api_v2_level_build_output_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelRowIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOutputResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_worksheet_api_v2_worksheets__worksheet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetReadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_worksheet_api_v2_worksheets__worksheet_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorksheetSaveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetReadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    worksheet_versions_api_v2_worksheets__worksheet_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_worksheet_api_v2_worksheets__worksheet_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_worksheet_api_v2_worksheets__worksheet_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vocab_api_v2_vocab_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vocab_api_v2_vocab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_vocab_api_v2_vocab__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_vocab_api_v2_vocab__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v2_motion_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionTemplateOut"][];
                };
            };
        };
    };
    create_template_api_v2_motion_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotionTemplateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_template_api_v2_motion_templates__template_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v2_motion_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_template_api_v2_motion_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MotionTemplatePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_templates_api_v2_motion_templates_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wi_preview_api_v2_worksheets__worksheet_id__export_wi_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_api_v2_worksheets__worksheet_id__export_excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_lb_csv_api_v2_worksheets__worksheet_id__export_lb_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_lb_api_api_v2_worksheets__worksheet_id__export_lb_api_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v2_imports_upload_post: {
        parameters: {
            query?: {
                worksheet_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v2_imports_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_columns_api_v2_imports__import_id__map_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_api_v2_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_v2_imports_profiles_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
        };
    };
    create_profile_api_v2_imports_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v2_imports_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rule_sets_api_v2_rule_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_full_api_v2_rule_sets__code__full_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_full_api_v2_rule_sets__code__full_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_draft_api_v2_rule_sets__code__clone_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneDraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v2_rule_sets__code__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v2_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUserOut"][];
                };
            };
        };
    };
    upsert_user_api_v2_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUserUpsertIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_api_v2_admin_users__employee_no__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_no: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppUserPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
