"""`MINIMOST_FACTORY_V2` seed —— v3 IE 認證字典（ADR-014 值權威）。

⚠️ AUTO-GENERATED by scripts/import_v3_dictionary.py — 禁止手改數值；
   改值＝改 docs/v3/reference/minimost_ai_dictionary_v1.json（IE 認證流程）後重跑轉換器。

與 V1 的裁決差異（詳 docs/v3/impl/impl-01）：M 階梯門檻修正為 cm 正確值（2.5/10/25/45/75，無 overflow 檔）；
M 腳步獨立帶（M_FOOT）；G gating 全關（選項即語意）；I 八檔（含視線外）；X 九檔；X 捨入 half-up（引擎 E2）。
"""
from __future__ import annotations

import uuid
from typing import Any

TMU_TO_SEC = 0.036

RULE_SET = {"code": "MINIMOST_FACTORY_V2", "name_zh": "MiniMOST 工廠規則 v2（v3 IE 認證）", "system_tmu_multiplier": 1}

# component, max_value(None=overflow), index, sort
A_BANDS = [
    ('reach', 2.5, 0, 0),
    ('reach', 5.0, 1, 1),
    ('reach', 10.0, 3, 2),
    ('reach', 20.0, 6, 3),
    ('reach', 35.0, 10, 4),
    ('reach', 60.0, 16, 5),
    ('reach', None, 24, 6),
    ('twist', 30.0, 0, 0),
    ('twist', 60.0, 1, 1),
    ('twist', 120.0, 3, 2),
    ('twist', 180.0, 6, 3),
    ('foot', 20.0, 6, 0),
    ('foot', 30.0, 10, 1),
    ('foot', 45.0, 16, 2),
    ('foot', 65.0, 24, 3),
    ('foot', None, 32, 4),
]

# code, label_zh, index, is_default, sort, sentence_zh（b_none 為轉換器注入）
B_OPTIONS = [
    ('b_none', '無身體動作', 0, True, 0, ''),
    ('b_eye', '眼部動作', 10, False, 1, '眼部動作'),
    ('b_bend', '起身或彎腰/坐', 32, False, 2, '起身或彎腰/坐'),
    ('b_stand', '站', 42, False, 3, '站'),
]

# code, label_zh, modifier_key(=None), requires_modifier(=False), base_tmu, sort, sentence_zh
G_ACTIONS = [
    ('g_tap', '輕按', None, False, 3, 0, '輕按'),
    ('g_touch', '接觸', None, False, 3, 1, '接觸'),
    ('g_pat', '輕拍', None, False, 3, 2, '輕拍'),
    ('g_grasp', '抓握', None, False, 6, 3, '抓握'),
    ('g_grab', '抓取', None, False, 6, 4, '抓取'),
    ('g_regrasp', '重新抓握', None, False, 6, 5, '重新抓握'),
    ('g_handchange', '換手(轉移)', None, False, 10, 6, '換手'),
    ('g_pick_sel', '拿取(選取)', None, False, 10, 7, '拿取'),
    ('g_pick_small', '拿取(選取-小)', None, False, 16, 8, '拿取'),
    ('g_pullout', '拔出(分離)', None, False, 16, 9, '拔出'),
    ('g_pick_collect', '拿取(收集)', None, False, 24, 10, '拿取'),
]

# code, label_zh, category, direction_mode, base_tmu, sort, sentence_zh
P_BASES = [
    ('p_toss', '丟', 'toss', None, 3, 0, '丟'),
    ('p_hold', '保持住', 'hold', None, 3, 1, '保持住'),
    ('p_place_none', '放(無方向)', 'place', 'none', 6, 2, '放'),
    ('p_place_multi', '放(多種方向)', 'place', 'multi', 10, 3, '放'),
    ('p_place_single', '放(一種方向)', 'place', 'single', 16, 4, '放'),
    ('p_asm_multi', '組(多種方向)', 'assemble', 'multi', 10, 5, '組'),
    ('p_asm_single', '組(一種方向)', 'assemble', 'single', 16, 6, '組'),
]

# code, label_zh, delta_tmu, needs_precision(=False), sort, display_rule, sentence_zh
P_ADDONS = [
    ('a_align', '對準(精度<4mm)', 8, False, 0, 'prefix_visible_term', '對準'),
    ('a_insert', '插入', 8, False, 1, 'show_self', '插入'),
    ('a_hard', '較難處理', 8, False, 2, 'hidden', ''),
    ('a_snap', '卡合', 16, False, 3, 'show_self', '卡合'),
    ('a_press', '施加壓力', 16, False, 4, 'hidden', ''),
]

# max_cm, tmu, sort ——【C1 定案】吋(cm) 正確值；無 overflow（>75 → 422）
M_LADDER = [
    (2.5, 3, 0),
    (10.0, 6, 1),
    (25.0, 10, 2),
    (45.0, 16, 3),
    (75.0, 24, 4),
]

# max_cm(None=overflow), tmu, sort ——【C2 定案】M 腳步獨立帶
M_FOOT = [
    (25.0, 10, 0),
    (40.0, 16, 1),
    (55.0, 24, 2),
    (75.0, 32, 3),
    (None, 42, 4),
]

# code, label_zh, pricing_kind, fixed_tmu, sort, sentence_zh
M_VERBS = [
    ('m_btn', '按動按鈕', 'fixed', 3, 0, '按動按鈕'),
    ('m_screw', '滑出螺絲', 'fixed', 3, 1, '滑出螺絲'),
    ('m_li', '理', 'ladder', None, 2, '理'),
    ('m_through', '穿', 'ladder', None, 3, '穿'),
    ('m_push', '推', 'ladder', None, 4, '推'),
    ('m_pull', '拉', 'ladder', None, 5, '拉'),
    ('m_attach', '貼附', 'ladder', None, 6, '貼附'),
    ('m_remove', '去除', 'ladder', None, 7, '去除'),
    ('m_teartape', '撕除', 'ladder', None, 8, '撕除'),
    ('m_fold', '折', 'ladder', None, 9, '折'),
    ('m_wipe', '擦拭', 'ladder', None, 10, '擦拭'),
    ('m_tearopen', '撕開', 'ladder', None, 11, '撕開'),
    ('m_rotate', '旋轉', 'rotate', None, 12, '旋轉'),
    ('m_press', '按壓', 'fixed', 3, 13, '按壓'),
    ('m_hand', '手度', 'hand', None, 14, ''),
    ('m_foot', '腳步', 'foot', None, 15, ''),
]

# max_diameter_cm, revolutions, tmu, sort ——無 D50 3圈/大直徑 overflow（殘項#2）
M_ROTATION = [
    (12.5, 1, 16, 0),
    (12.5, 2, 32, 1),
    (12.5, 3, 42, 2),
    (50.0, 1, 24, 3),
    (50.0, 2, 42, 4),
]

# max_deg, tmu, sort ——≤180 封頂（>180 → 422）
M_HAND = [
    (90.0, 6, 0),
    (180.0, 10, 1),
]

# code, label_zh, mode, fixed_seconds, sort, sentence_zh（x_none 為轉換器注入）
X_OPTIONS = [
    ('x_none', '無機台等待', 'zero', None, 0, ''),
    ('x_press', '並壓合機台', 'seconds', None, 1, '並壓合機台'),
    ('x_snap_press', '並卡合&壓合機台', 'seconds', None, 2, '並卡合&壓合機台'),
    ('x_heat', '並熱熔機台', 'seconds', None, 3, '並熱熔機台'),
    ('x_glue', '並點膠', 'seconds', None, 4, '並點膠'),
    ('x_screw_fix', '並鎖附固定(鎖附順序如圖所示)', 'fixed', 0.216, 5, '並鎖附固定'),
    ('x_laser', '並鐳雕', 'seconds', None, 6, '並鐳雕'),
    ('x_scan_ppid', '刷PPID', 'fixed', 0.216, 7, '刷PPID'),
    ('x_scan_wo', '刷工單二維碼', 'fixed', 0.216, 8, '刷工單二維碼'),
    ('x_scan_bar', '刷條形碼', 'fixed', 0.216, 9, '刷條形碼'),
    ('x_blow_clean', '並吹風清潔', 'seconds', None, 10, '並吹風清潔'),
]

# code, label_zh, index, sort, vision_scope, sentence_zh（i_none 為轉換器注入）
I_OPTIONS = [
    ('i_none', '不額外對齊', 0, 0, None, ''),
    ('i_check', '並檢查(正常視線範圍)', 6, 1, 'normal', '並檢查'),
    ('i_confirm', '並確認(正常視線範圍)', 6, 2, 'normal', '並確認'),
    ('i_align1', '並對準(正常視線範圍到點)', 10, 3, 'normal', '並對準'),
    ('i_align2', '並對齊(正常視線範圍到兩點)', 16, 4, 'normal', '並對齊'),
    ('i_check_out', '並檢查(正常視線範圍外)', 16, 5, 'outside', '並檢查'),
    ('i_confirm_out', '並確認(正常視線範圍外)', 16, 6, 'outside', '並確認'),
    ('i_align1_out', '並對準(正常視線範圍外到點)', 24, 7, 'outside', '並對準'),
    ('i_align2_out', '並對齊(正常視線範圍外到兩點)', 32, 8, 'outside', '並對齊'),
]



# ───────────────────────── DB 插入 ─────────────────────────
def seed_rule_set_factory_v2(session: Any) -> Any:
    """插入 V2 rule-set 與所有子表（published）。idempotent 由呼叫端以 code 查重。回傳 RuleSet。"""
    from ddm_v2.models.v2 import rule_set_tables as rt
    from ddm_v2.models.v2.rule_set import RuleSet

    rs = RuleSet(id=uuid.uuid4(), code=RULE_SET["code"], name_zh=RULE_SET["name_zh"],
                 status="published", system_tmu_multiplier=RULE_SET["system_tmu_multiplier"])
    session.add(rs)
    _id = uuid.uuid4

    for comp, mx, iv, so in A_BANDS:
        session.add(rt.RuleABand(id=_id(), rule_set_id=rs.id, component=comp, max_value=mx, index_value=iv, sort_order=so))
    for code, lab, iv, dft, so, sent in B_OPTIONS:
        session.add(rt.RuleBOption(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, index_value=iv,
                                   is_default=dft, sort_order=so, sentence_text_zh=sent or None))
    for code, lab, mod, req, tmu, so, sent in G_ACTIONS:
        session.add(rt.RuleGAction(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, modifier_key=mod,
                                   requires_modifier=req, base_tmu=tmu, sort_order=so, sentence_text_zh=sent or None))
    for code, lab, cat, dm, tmu, so, sent in P_BASES:
        session.add(rt.RulePBase(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, category=cat,
                                 direction_mode=dm, base_tmu=tmu, sort_order=so, sentence_text_zh=sent or None))
    for code, lab, dt, prec, so, drule, sent in P_ADDONS:
        session.add(rt.RulePAddon(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, delta_tmu=dt,
                                  needs_precision=prec, sort_order=so, display_rule=drule, sentence_text_zh=sent or None))
    for mx, tmu, so in M_LADDER:
        session.add(rt.RuleMLadderBand(id=_id(), rule_set_id=rs.id, max_cm=mx, tmu=tmu, sort_order=so))
    for mx, tmu, so in M_FOOT:
        session.add(rt.RuleMFootBand(id=_id(), rule_set_id=rs.id, max_cm=mx, tmu=tmu, sort_order=so))
    for code, lab, kind, ftmu, so, sent in M_VERBS:
        session.add(rt.RuleMVerb(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, pricing_kind=kind,
                                 fixed_tmu=ftmu, sort_order=so, sentence_text_zh=sent or None))
    for mx, rev, tmu, so in M_ROTATION:
        session.add(rt.RuleMRotationBand(id=_id(), rule_set_id=rs.id, max_diameter_cm=mx, revolutions=rev, tmu=tmu, sort_order=so))
    for mx, tmu, so in M_HAND:
        session.add(rt.RuleMHandBand(id=_id(), rule_set_id=rs.id, max_deg=mx, tmu=tmu, sort_order=so))
    for code, lab, mode, fsec, so, sent in X_OPTIONS:
        session.add(rt.RuleXOption(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, mode=mode,
                                   fixed_seconds=fsec, sort_order=so, sentence_text_zh=sent or None))
    for code, lab, iv, so, scope, sent in I_OPTIONS:
        session.add(rt.RuleIOption(id=_id(), rule_set_id=rs.id, code=code, label_zh=lab, index_value=iv,
                                   sort_order=so, vision_scope=scope, sentence_text_zh=sent or None))
    return rs


# ───────────── 自我驗證（黃金錨；引擎重錨見 impl-02 E8）─────────────
def _self_check() -> int:
    from ddm_v2.most_engine import compute_cycle
    from ddm_v2.most_engine.providers import build_from_seed_v2

    rs = build_from_seed_v2()

    def _a(reach=0):
        return {"reach_cm": reach}

    gm = compute_cycle({"seq": "GM", "slots": {0: _a(20), 1: {}, 2: {"g_code": "g_grasp"}, 3: {"reach_cm": 25}, 4: {}, 5: {"p_base_code": "p_place_none"}, 6: _a()}}, rs)
    cm = compute_cycle({"seq": "CM", "slots": {0: _a(25), 1: {}, 2: {"g_code": "g_touch"}, 3: {"m_components": [{"verb_code": "m_push", "distance_cm": 45}]}, 4: {"x_code": "x_none"}, 5: {"i_code": "i_none"}, 6: _a()}}, rs)
    checks = [
        ("GM 黃金 = 28", gm.total_tmu == 28),
        ("CM 黃金 = 29（推 45cm=18 吋檔）", cm.total_tmu == 29),
        ("M 推 30cm → 16（≤45 檔）", rs.ladder_tmu(30) == 16),
        ("M 腳步 30cm → 16（foot 帶 ≤40）", rs.foot_tmu(30) == 16),
        ("X 10s → 277.778（half-up）", abs(rs.seconds_to_tmu(10) - 277.778) < 1e-9),
        ("X 0.216s → 6", abs(rs.seconds_to_tmu(0.216) - 6.0) < 1e-9),
        ("G 接觸（無 gating）→ 3", rs.g_actions["g_touch"].base_tmu == 3 and not rs.g_actions["g_touch"].requires_modifier),
        ("I 視線外對齊兩點 → 32", rs.i_index["i_align2_out"] == 32),
        ("B 值 = {0,10,32,42}", {r[2] for r in B_OPTIONS} == {0, 10, 32, 42}),
        ("M ladder 無 overflow（>75 應由引擎報錯）", M_LADDER[-1][0] == 75.0),
    ]
    fails = 0
    for name, ok in checks:
        print(f"  {'✅' if ok else '❌'} {name}")
        fails += 0 if ok else 1
    print(f"\n{'='*46}\nV2 seed 驗證：{'✅ 全部通過' if fails == 0 else f'❌ {fails} 項失敗'}\n{'='*46}")
    return 0 if fails == 0 else 1


if __name__ == "__main__":
    import sys
    sys.exit(_self_check())
